spring:
    application:
        name: law-project
    profiles:
        active: home
    datasource:
        druid:
            driver-class-name: org.postgresql.Driver
            # 初始化连接数量
            initial-size: 5
            # 最小线连接数量
            min-idle: 5
            # 最大连接数量
            max-active: 20
            # 获取连接时最大等待时间，单位毫秒
            max-wait: 60000
            #销毁线程时检测当前连接的最后活动时间和当前时间差大于该值时，关闭当前连接
            min-evictable-idle-time-millis: 30000
            #用来检测连接是否有效的sql 必须是一个查询语句
            #mysql中为 select 'x'
            #oracle中为 select 1 from dual
            validation-query: select 'x'
            #申请连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
            test-on-borrow: false
            #归还连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为tru
            test-on-return: false
            #配置过滤器，过滤掉静态文件
            web-stat-filter:
                enabled: true
                url-pattern: /*
                exclusions: /druid/*,*.js,*.css,*.gif,*.jpg,*.bmp,*.png,*.ico
            # 配置后台监控
            stat-view-servlet:
                # 可以访问界面
                url-pattern: /druid/*
                # 允许访问的地址，这里因为时本地所以配置当前机器
                allow: 127.0.0.1
                # 是否开启访问
                enabled: true
                # 是否能够重置数据
                reset-enable: false
                # 管理页面登陆的用户名
                login-username: admin
                # 管理页面登陆的密码
                login-password: admin
mybatis-plus:
    mapper-locations: classpath*:mapper/*.xml
    configuration:
        map-underscore-to-camel-case: true
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
        use-generated-keys: true
    global-config:
        db-config:
            id-type: auto
    type-aliases-package: com.law.rag.entity
